# Generated by Django 3.1.7 on 2021-03-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_roomstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='room_state',
            field=models.CharField(choices=[('DND', 'Bitte nicht stören!'), ('OPN', 'Wir haben geöffnet!'), ('CLS', 'Wir haben geschlossen!'), ('BRB', 'Wir haben gleich wieder geöffnet!')], default='OPN', max_length=3, verbose_name='Raumzustand'),
        ),
    ]
