# Generated by Django 3.1.7 on 2021-03-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_room_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStateChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_state', models.CharField(choices=[('DND', 'Bitte nicht stören!'), ('OPN', 'Wir haben geöffnet!'), ('CLS', 'Wir haben geschlossen!'), ('BRB', 'Wir haben gleich wieder geöffnet!')], default='OPN', max_length=3, verbose_name='Raumzustand')),
            ],
        ),
    ]
