# Generated by Django 3.1.7 on 2021-04-07 07:40

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_roomstatechoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomStateChoice',
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage', 'verbose_name_plural': 'Homepages'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(verbose_name='Details zur Nachricht des Tages'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Nachricht des Tages'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='room_state',
            field=models.CharField(choices=[('DND', 'Bitte nicht stören!'), ('OPN', 'Wir haben geöffnet!'), ('CLS', 'Wir haben geschlossen!'), ('BRB', 'Wir haben gleich wieder geöffnet!')], default='OPN', max_length=3, verbose_name='Raum-Status'),
        ),
    ]
