# Generated by Django 3.1.7 on 2021-03-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_state', models.CharField(choices=[('DND', 'Do not disturb!'), ('OPN', 'We are open!'), ('CLS', 'We are closed!')], default='OPN', max_length=3)),
            ],
        ),
    ]
