# Generated by Django 3.1.7 on 2021-03-29 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roomstate', '0002_auto_20210329_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstate',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 9, 47, 2, 294136, tzinfo=utc), verbose_name='date published'),
        ),
    ]
