# Generated by Django 3.1.7 on 2021-03-29 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roomstate', '0004_auto_20210329_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstate',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 9, 51, 2, 176412, tzinfo=utc), verbose_name='Erstelldatum'),
        ),
        migrations.AlterField(
            model_name='roomstate',
            name='room_state',
            field=models.CharField(choices=[('DND', 'Bitte nicht stören!'), ('OPN', 'Wir haben geöffnet!'), ('CLS', 'Wir haben geschlossen!'), ('BRB', 'Wir haben gleich wieder geöffnet!')], default='OPN', max_length=3, verbose_name='Raumzustand'),
        ),
    ]
