# Generated by Django 3.1.7 on 2021-03-29 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roomstate', '0005_auto_20210329_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstate',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 10, 36, 3, 976379, tzinfo=utc), verbose_name='Erstelldatum'),
        ),
    ]
